services:
  drupal:
    build: ./
    container_name: ${APP_NAME}-drupal
    ports:
      - ${DRUPAL_PORT}:80
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - drupal
    env_file:
      - .env
    volumes:
      - ${DRUPAL_LOCAL_THEMES}:/var/www/html/themes
      - ${DRUPAL_LOCAL_MODULES}:/var/www/html/modules
      - ${UPLOADS_CONFIG}:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      - DRUPAL_DB_HOST=${DRUPAL_DB_HOST}
      - DRUPAL_DB_NAME=${DRUPAL_DB_NAME}
      - DRUPAL_DB_USER=${DRUPAL_DB_USER}
      - DRUPAL_DB_PASSWORD=${DRUPAL_DB_PASSWORD}

  database:
    ports:
      - ${MYSQL_PORT}:3306
    image: mysql:8
    container_name: ${APP_NAME}-database
    restart: unless-stopped
    networks:
      - drupal
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_LOCAL_HOME}:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - ${PHPMYADMIN_PORT}:80
    depends_on:
      - database
    networks:
      - drupal
    links:
      - database
    env_file:
      - .env
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${APP_NAME}-database
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}

networks:
  drupal:
    name: ${APP_NAME}-net
    driver: bridge
